// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhe-1G6jn_GuT5aVAaXJlpdGI4N76ZbPA',
    appId: '1:1098332878968:web:4b7be25268ab05279c158d',
    messagingSenderId: '1098332878968',
    projectId: 'tracking-app-35310',
    authDomain: 'tracking-app-35310.firebaseapp.com',
    storageBucket: 'tracking-app-35310.appspot.com',
    measurementId: 'G-20D7CGNQ4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDquDKxZpFvsOOBOK6XvwePybT0lttFi_M',
    appId: '1:1098332878968:android:e57e2ba61c0a282a9c158d',
    messagingSenderId: '1098332878968',
    projectId: 'tracking-app-35310',
    storageBucket: 'tracking-app-35310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaBMHkrbxsoK8H-nPWvlz9aGQVHj2k5Tc',
    appId: '1:1098332878968:ios:0ffc8c5717d491939c158d',
    messagingSenderId: '1098332878968',
    projectId: 'tracking-app-35310',
    storageBucket: 'tracking-app-35310.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaBMHkrbxsoK8H-nPWvlz9aGQVHj2k5Tc',
    appId: '1:1098332878968:ios:0ffc8c5717d491939c158d',
    messagingSenderId: '1098332878968',
    projectId: 'tracking-app-35310',
    storageBucket: 'tracking-app-35310.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhe-1G6jn_GuT5aVAaXJlpdGI4N76ZbPA',
    appId: '1:1098332878968:web:20a84a762873c8ea9c158d',
    messagingSenderId: '1098332878968',
    projectId: 'tracking-app-35310',
    authDomain: 'tracking-app-35310.firebaseapp.com',
    storageBucket: 'tracking-app-35310.appspot.com',
    measurementId: 'G-939QY9QWLT',
  );
}
